//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zongsoft.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zongsoft.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 清除当前终端的显示内容。 的本地化字符串。
        /// </summary>
        internal static string ClearCommand_Description {
            get {
                return ResourceManager.GetString("ClearCommand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除命令。 的本地化字符串。
        /// </summary>
        internal static string ClearCommand_Title {
            get {
                return ResourceManager.GetString("ClearCommand.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令 的本地化字符串。
        /// </summary>
        internal static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述： 的本地化字符串。
        /// </summary>
        internal static string CommandDescription {
            get {
                return ResourceManager.GetString("CommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; 命令没有找到。 的本地化字符串。
        /// </summary>
        internal static string CommandNotFound {
            get {
                return ResourceManager.GetString("CommandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令选项： 的本地化字符串。
        /// </summary>
        internal static string CommandOptions {
            get {
                return ResourceManager.GetString("CommandOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用法： 的本地化字符串。
        /// </summary>
        internal static string CommandUsages {
            get {
                return ResourceManager.GetString("CommandUsages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用 的本地化字符串。
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos;是无效的命令参数值。 的本地化字符串。
        /// </summary>
        internal static string InvalidCommandArgumentValue {
            get {
                return ResourceManager.GetString("InvalidCommandArgumentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos;是一个无效的命令选项。 的本地化字符串。
        /// </summary>
        internal static string InvalidCommandOption {
            get {
                return ResourceManager.GetString("InvalidCommandOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{1}&apos;是一个无效的&apos;{0}&apos;命令选项值。 的本地化字符串。
        /// </summary>
        internal static string InvalidCommandOptionValue {
            get {
                return ResourceManager.GetString("InvalidCommandOptionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺失命令参数，请为该命令指定一个输入参数。 的本地化字符串。
        /// </summary>
        internal static string MissingCommandArgument {
            get {
                return ResourceManager.GetString("MissingCommandArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺失&apos;{0}&apos;命令选项，该选项为必须项。 的本地化字符串。
        /// </summary>
        internal static string MissingCommandOption {
            get {
                return ResourceManager.GetString("MissingCommandOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可选 的本地化字符串。
        /// </summary>
        internal static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须 的本地化字符串。
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帐户已被封。 的本地化字符串。
        /// </summary>
        internal static string Text_AuthenticationReason_AccountDisabled {
            get {
                return ResourceManager.GetString("Text.AuthenticationReason.AccountDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帐户被暂停，可能是因为验证失败次数太多。 的本地化字符串。
        /// </summary>
        internal static string Text_AuthenticationReason_AccountSuspended {
            get {
                return ResourceManager.GetString("Text.AuthenticationReason.AccountSuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帐户尚未通过审核批准。 的本地化字符串。
        /// </summary>
        internal static string Text_AuthenticationReason_AccountUnapproved {
            get {
                return ResourceManager.GetString("Text.AuthenticationReason.AccountUnapproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁止访问，您的账号没有被授权访问当前资源。 的本地化字符串。
        /// </summary>
        internal static string Text_AuthenticationReason_Forbidden {
            get {
                return ResourceManager.GetString("Text.AuthenticationReason.Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的身份标识。 的本地化字符串。
        /// </summary>
        internal static string Text_AuthenticationReason_InvalidIdentity {
            get {
                return ResourceManager.GetString("Text.AuthenticationReason.InvalidIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的密码。 的本地化字符串。
        /// </summary>
        internal static string Text_AuthenticationReason_InvalidPassword {
            get {
                return ResourceManager.GetString("Text.AuthenticationReason.InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证成功 的本地化字符串。
        /// </summary>
        internal static string Text_AuthenticationReason_Succeed {
            get {
                return ResourceManager.GetString("Text.AuthenticationReason.Succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证失败 的本地化字符串。
        /// </summary>
        internal static string Text_AuthenticationReason_Unknown {
            get {
                return ResourceManager.GetString("Text.AuthenticationReason.Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁止访问，您没有访问这项资源的授权。 的本地化字符串。
        /// </summary>
        internal static string Text_AuthorizationException_Message {
            get {
                return ResourceManager.GetString("Text.AuthorizationException.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缓存过期 的本地化字符串。
        /// </summary>
        internal static string Text_CollectionRemovedReason_Expired {
            get {
                return ResourceManager.GetString("Text.CollectionRemovedReason.Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他原因 的本地化字符串。
        /// </summary>
        internal static string Text_CollectionRemovedReason_Other {
            get {
                return ResourceManager.GetString("Text.CollectionRemovedReason.Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 集合溢出 的本地化字符串。
        /// </summary>
        internal static string Text_CollectionRemovedReason_Overflow {
            get {
                return ResourceManager.GetString("Text.CollectionRemovedReason.Overflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动删除 的本地化字符串。
        /// </summary>
        internal static string Text_CollectionRemovedReason_Remove {
            get {
                return ResourceManager.GetString("Text.CollectionRemovedReason.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 执行失败。 的本地化字符串。
        /// </summary>
        internal static string Text_Command_ExecutionFailed_Message {
            get {
                return ResourceManager.GetString("Text.Command.ExecutionFailed.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 执行成功。 的本地化字符串。
        /// </summary>
        internal static string Text_Command_ExecutionSucceed_Message {
            get {
                return ResourceManager.GetString("Text.Command.ExecutionSucceed.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令出错： 的本地化字符串。
        /// </summary>
        internal static string Text_CommandError_Label {
            get {
                return ResourceManager.GetString("Text.CommandError.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 凭证错误：指定的凭证是无效的或已经过期。 的本地化字符串。
        /// </summary>
        internal static string Text_CredentialException_Message {
            get {
                return ResourceManager.GetString("Text.CredentialException.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据访问发生异常，请与您的系统管理员联系。 的本地化字符串。
        /// </summary>
        internal static string Text_DataAccessException_Message {
            get {
                return ResourceManager.GetString("Text.DataAccessException.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据冲突：数据项中 {0} 的 {1} 值重复了。 的本地化字符串。
        /// </summary>
        internal static string Text_DataConflictException_Message {
            get {
                return ResourceManager.GetString("Text.DataConflictException.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确认是否要退出(输入Yes则退出)？ 的本地化字符串。
        /// </summary>
        internal static string Text_ExitCommand_Confirm {
            get {
                return ResourceManager.GetString("Text.ExitCommand.Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出当前应用程序。 的本地化字符串。
        /// </summary>
        internal static string Text_ExitCommand_Description {
            get {
                return ResourceManager.GetString("Text.ExitCommand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直接退出，不提示确认信息。 的本地化字符串。
        /// </summary>
        internal static string Text_ExitCommand_Options_Confirm {
            get {
                return ResourceManager.GetString("Text.ExitCommand.Options.Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出命令 的本地化字符串。
        /// </summary>
        internal static string Text_ExitCommand_Title {
            get {
                return ResourceManager.GetString("Text.ExitCommand.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这是一个侦听消息队列的后台服务程序，它以堵塞方式不断轮询消息队列(即循环以堵塞式调用消息队列的出队方法)，一旦队列中有消息可用则立即将消息出队，然后交给侦听器中的执行器去执行。 的本地化字符串。
        /// </summary>
        internal static string Text_MessageQueueListener_Description {
            get {
                return ResourceManager.GetString("Text.MessageQueueListener.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zongsoft 消息队列侦听器 的本地化字符串。
        /// </summary>
        internal static string Text_MessageQueueListener_Title {
            get {
                return ResourceManager.GetString("Text.MessageQueueListener.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码生成操作调用太频繁，请等待一会后再来。 的本地化字符串。
        /// </summary>
        internal static string Text_SecretGenerateTooFrequently_Message {
            get {
                return ResourceManager.GetString("Text.SecretGenerateTooFrequently.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通过系统Shell来执行外部命令。 的本地化字符串。
        /// </summary>
        internal static string Text_ShellCommand_Description {
            get {
                return ResourceManager.GetString("Text.ShellCommand.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行外部命令的超时，单位：毫秒。 的本地化字符串。
        /// </summary>
        internal static string Text_ShellCommand_Options_Timeout {
            get {
                return ResourceManager.GetString("Text.ShellCommand.Options.Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外部命令执行者 的本地化字符串。
        /// </summary>
        internal static string Text_ShellCommand_Title {
            get {
                return ResourceManager.GetString("Text.ShellCommand.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示：按 Ctrl+C 组合键可以退出侦听模式。 的本地化字符串。
        /// </summary>
        internal static string Text_WorkerListenCommand_Prompt {
            get {
                return ResourceManager.GetString("Text.WorkerListenCommand.Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎进入 {0} 的侦听模式。 的本地化字符串。
        /// </summary>
        internal static string Text_WorkerListenCommand_Welcome {
            get {
                return ResourceManager.GetString("Text.WorkerListenCommand.Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停 的本地化字符串。
        /// </summary>
        internal static string Text_WorkerPauseCommand_Name {
            get {
                return ResourceManager.GetString("Text.WorkerPauseCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复 的本地化字符串。
        /// </summary>
        internal static string Text_WorkerResumeCommand_Name {
            get {
                return ResourceManager.GetString("Text.WorkerResumeCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        internal static string Text_WorkerStartCommand_Name {
            get {
                return ResourceManager.GetString("Text.WorkerStartCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已暂停 的本地化字符串。
        /// </summary>
        internal static string Text_WorkerState_Paused {
            get {
                return ResourceManager.GetString("Text.WorkerState.Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停中 的本地化字符串。
        /// </summary>
        internal static string Text_WorkerState_Pausing {
            get {
                return ResourceManager.GetString("Text.WorkerState.Pausing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复中 的本地化字符串。
        /// </summary>
        internal static string Text_WorkerState_Resuming {
            get {
                return ResourceManager.GetString("Text.WorkerState.Resuming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行中 的本地化字符串。
        /// </summary>
        internal static string Text_WorkerState_Running {
            get {
                return ResourceManager.GetString("Text.WorkerState.Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动中 的本地化字符串。
        /// </summary>
        internal static string Text_WorkerState_Starting {
            get {
                return ResourceManager.GetString("Text.WorkerState.Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未运行 的本地化字符串。
        /// </summary>
        internal static string Text_WorkerState_Stopped {
            get {
                return ResourceManager.GetString("Text.WorkerState.Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止中 的本地化字符串。
        /// </summary>
        internal static string Text_WorkerState_Stopping {
            get {
                return ResourceManager.GetString("Text.WorkerState.Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        internal static string Text_WorkerStopCommand_Name {
            get {
                return ResourceManager.GetString("Text.WorkerStopCommand.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取值范围： 的本地化字符串。
        /// </summary>
        internal static string ValueRange {
            get {
                return ResourceManager.GetString("ValueRange", resourceCulture);
            }
        }
    }
}
